Repository 2023-Winter-Bootcamp-Team-K/Front, pull requests merged in 2024-01, with the labels that each got.

#3 [Design/#2]로그인 인풋 퍼블리싱
  src/App.tsx
  src/components/common/LoginInput.tsx
Labels: 🎨Design

#12 [Design/#8] 로그인 인풋 styled component 퍼블리싱
  src/App.tsx
  src/components/common/LoginInput.tsx
  src/main.tsx
  src/styles/GlobalStyle.ts
Labels: 🎨Design

#14 [Design/#10] styled component로 변환 및 이름 변경
  src/components/common/Btn.tsx
  src/components/common/RectangleBtn.tsx
  src/components/common/RectangleButton.tsx
  src/components/common/RoundButton.tsx
Labels: 🎨Design

#16 [Design/#11] 내 대화창, 상대방 대화창 컴포넌트 생성
  src/components/common/MyMessage.tsx
  src/components/common/OpponentMessage.tsx
Labels: 🎨Design

#17 [Design/#13] 로그인 페이지 생성, 버튼 활성화
  src/App.tsx
  src/assets/img/Login_bg.png
  src/components/common/Btn.tsx
  src/components/common/LoginInput.tsx
  src/pages/LogInPage.tsx
  src/router.tsx
Labels: 🎨Design

#19 [Design/#9]감정 표현 모달
  src/components/modal/Modal.tsx
Labels: 🎨Design

#20 [Design/#15]쿼카 컴포넌트 구현
  src/assets/img/SpeakingQuakka.png
  src/assets/img/mingcute_voice-fill.svg
  src/components/common/CharComponent.tsx
Labels: 🎨Design

#24 [Design/#18]로그인 회원가입 버튼 컴포넌트 props추가
  src/assets/SVG.tsx
  src/assets/img/checkb.png
  src/components/common/Btn.tsx
  src/components/common/LoginInput.tsx
  src/components/common/RectangleBtn.tsx
  src/pages/LogInPage.tsx
  src/pages/SignupPage.tsx
  src/router.tsx
Labels: 🎨Design

#27 인트로 페이지 퍼블리싱
  src/assets/img/인트로페이지.png
  src/components/common/Btn.tsx
  src/pages/IntroPage.tsx
  src/pages/SignupPage.tsx
  src/router.tsx
Labels: 🎨Design

#29 [design/#22메인 페이지 퍼블리싱
  src/assets/SVG.tsx
  src/assets/img/Main_bg.png
  src/pages/MainPage.tsx
  src/router.tsx
Labels: 🎨Design

#31 [design/#28] 채팅 컴포넌트
  src/assets/SVG.tsx
  src/components/common/Chatting.tsx
Labels: 🎨Design

#34 [design/#32]카메라 컴포넌트 퍼블리싱(중간점검)
  package.json
  src/components/common/Camera.tsx
  src/router.tsx
  yarn.lock
Labels: 🎨Design

#36 [design/#25] 달력 컴포넌트 퍼블리싱
  package.json
  src/App.tsx
  src/components/calender/Calender.tsx
  src/components/calender/CalenderStyle.tsx
  src/components/modal/Modal.tsx
  yarn.lock
Labels: 🎨Design

#37 [design/#35] diary 컴포넌트 퍼블리싱
  src/assets/img/Diary_Text.png
  src/components/common/Diary.tsx
  src/router.tsx
Labels: 🎨Design

#40 [design/#33] ChatPage 퍼블리싱 및 컴포넌트 수정
  src/assets/SVG.tsx
  src/assets/img/Chat_bg.png
  src/assets/img/QuitIcon.png
  src/components/common/Camera.tsx
  src/components/common/CharComponent.tsx
  src/components/common/Chatting.tsx
  src/pages/ChatPage.tsx
  src/router.tsx
Labels: 🎨Design

#41 [design/#38] 로그인 페이지 반응형 생성
  src/assets/img/LoginPage_p_bg.png
  src/assets/img/쿼카.png
  src/components/common/Btn.tsx
  src/components/common/LoginInput.tsx
  src/pages/LogInPage.tsx
Labels: 🎨Design

#42 [design/#39] 인트로 페이지 반응형 생성
  src/assets/img/introP.png
  src/pages/IntroPage.tsx
Labels: 🎨Design

#48 [design/#47] 모달 반응형 감정 변경
  src/components/common/Btn.tsx
  src/components/common/LoginInput.tsx
  src/components/modal/Modal.tsx
  src/pages/LogInPage.tsx
  src/router.tsx
Labels: 🎨Design

#49 [Design/#21]일기 퍼블리싱
  src/assets/img/Chat_bg.png
  src/assets/img/Cover.png
  src/assets/img/MainBG.png
  src/assets/img/book.png
  src/assets/img/diaryRightSide.png
  src/pages/BookCover.tsx
  src/pages/Diary.tsx
  src/router.tsx
Labels: 🎨Design

#52 [Design/#51]일기 퍼블리싱
  src/pages/DiaryPage.tsx
  src/router.tsx
Labels: 🎨Design

#54 [Design/#50] 카메라 반응형 구현
  src/assets/SVG.tsx
  src/assets/img/Mic.png
  src/components/common/Camera.tsx
  src/pages/ChatPage.tsx
  src/router.tsx
Labels: 🎨Design

#56 [Design/#53]챗박스 반응형
  src/components/common/MyMessage.tsx
  src/components/common/OpponentMessage.tsx
Labels: 🎨Design

#58 [Design/#53] 일기장 반응형 컴포넌트 설정
  src/assets/img/Diary_Text_P.png
  src/components/common/Diary.tsx
  src/pages/DiaryPage.tsx
  src/router.tsx
Labels: 🎨Design

#60 [design/#59] chattingresult 컴포넌트no 반응 result 페이지 no 반응
  src/components/common/ChattingResult.tsx
  src/pages/Result.tsx
  src/router.tsx
Labels: 🎨Design

#62 [Design/#57]채팅 컴포넌트 반응형, 로티 적용
  package.json
  public/vite.svg
  src/assets/img/BlackMic.png
  src/assets/lottie/Animation - 1704999772308.json
  src/assets/lottie/Mic.json
  src/components/common/Camera.tsx
  src/components/common/CharComponent.tsx
  src/components/common/Chatting.tsx
  src/components/common/MyMessage.tsx
  src/components/common/OpponentMessage.tsx
  src/components/gif/Mic.tsx
  src/components/gif/Voice.tsx
  yarn.lock
Labels: 🎨Design

#64 [Design/#63]로그인 인풋 정렬 수정
  src/components/common/LoginInput.tsx
  src/pages/LogInPage.tsx
Labels: 🎨Design

#65 [Design/#61] camera 모달 추가 (반응형O)
  package.json
  src/components/modal/CameraModal.tsx
  src/router.tsx
  yarn.lock
Labels: 🎨Design

#66 [design/#43] 메인 페이지 반응형 생성
  src/assets/img/mainP.png
  src/components/calender/CalenderStyle.tsx
  src/components/common/RectangleBtn.tsx
  src/pages/IntroPage.tsx
  src/pages/MainPage.tsx
Labels: 🎨Design

#70 [design/#69] chatInfo 컴포넌트 생성 및 chatpage 레이아웃 조정
  src/components/common/ChatInfo.tsx
  src/components/common/Chatting.tsx
  src/pages/ChatPage.tsx
  src/stores/toggle.ts
Labels: 🎨Design

#72 [Feat/#67]로그인 axios 연결
  package.json
  public/mockServiceWorker.js
  src/api/config.ts
  src/api/login/login.ts
  src/components/common/Btn.tsx
  src/components/common/LoginInput.tsx
  src/hooks/useInput.ts
  src/mocks/servers.ts
  src/pages/IntroPage.tsx
  src/pages/LogInPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignupPage.tsx
  yarn.lock
Labels: ✨Feat

#76 [feat/#74]로그인 api연결 완
  package.json
  src/App.tsx
  src/components/common/Btn.tsx
  src/pages/LogInPage.tsx
  src/utils/cookie.ts
  yarn.lock
Labels: ✨Feat

#75 [feat/#73]회원가입 axios 연결
  src/components/common/Btn.tsx
  src/components/common/LoginInput.tsx
  src/pages/SignupPage.tsx
Labels: ✨Feat

#86 [design/#81] DiaryPage 반응형 퍼블리싱
  src/assets/SVG.tsx
  src/assets/img/Diary_bg.png
  src/assets/img/HeartBubble.png
  src/pages/DiaryPage.tsx
Labels: 🎨Design

#87 [feat/#78] 일기 단일 조회 api 연동
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/api/diary.ts
  src/components/common/Diary.tsx
  src/pages/DiaryPage.tsx
  yarn.lock
Labels: ✨Feat

#89 [feat/#85] 웹소켓 연결 밎 console로그 오류 해결
  index.html
  src/components/common/ChatInfo.tsx
  src/components/modal/Modal.tsx
  src/pages/ChatPage.tsx
  src/pages/DiaryPage.tsx
  src/stores/toggle.ts
  src/styles/GlobalStyle.ts
Labels: ✨Feat

#94 [Feat/#79]메인페이지 달력 일정 axios 연결
  src/api/calender/calender.ts
  src/components/calender/Calender.tsx
  src/pages/MainPage.tsx
Labels: ✨Feat

#99 [Feat/#91] 사진 촬영 api 연동
  package.json
  src/components/modal/CameraModal.tsx
  src/pages/DiaryPage.tsx
  yarn.lock
Labels: ✨Feat

#101 [Design/#100] 노란 오류 해결 (Typescript 콘솔 오류)
  src/components/common/Btn.tsx
  src/components/common/LoginInput.tsx
Labels: 🎨Design

#104 [feat/#102] 페이지 이동 및 백그라운드 이미지 안뜨는거 해결
  src/components/modal/CameraModal.tsx
  src/pages/ChatPage.tsx
  src/pages/DiaryPage.tsx
Labels: ✨Feat

#105 [Feat/#95] 달력 일정 누르면 해당 일기 조회
  src/components/calender/Calender.tsx
  src/components/calender/CalenderStyle.tsx
  src/pages/BookCover.tsx
Labels: ✨Feat

#108 [feat/#98] 녹음 기능 구현
  src/components/common/AudioRecorder.tsx
  src/components/common/Camera.tsx
  src/components/common/Chatting.tsx
  src/pages/ChatPage.tsx
  src/stores/chat.ts
Labels: ✨Feat

#110 [feat/#107] 일기 전체조회 axios 연결 및 디자인 일부 수정
  src/pages/DiaryPage.tsx
Labels: ✨Feat

#114 [feat/#113]북커버 axios 연결
  src/components/common/Diary.tsx
  src/pages/BookCover.tsx
  src/pages/ChatPage.tsx
  src/pages/DiaryPage.tsx
Labels: ✨Feat

#115 [feat/#112] 아이디 중복확인 api 연동 및 다음 버튼 수정
  src/components/common/Btn.tsx
  src/pages/SignupPage.tsx
Labels: ✨Feat

#117 [design/#116] 로딩 페이지 구현 및 이미지 모달 생성
  package.json
  src/LoadingFallback.tsx
  src/components/modal/ImageModal.tsx
  src/pages/IntroPage.tsx
  src/router.tsx
  yarn.lock
Labels: 🎨Design

#120 [design/#119] 로딩 페이지 반응형 생성
  src/LoadingFallback.tsx
Labels: 🎨Design

#125 [Feat/#122] gif/정적이미지 처리
  src/assets/SVG.tsx
  src/assets/img/mingcute_voice-fill.svg
  src/components/common/AudioRecorder.tsx
  src/components/common/CharComponent.tsx
  src/components/modal/Modal.tsx
Labels: ✨Feat

#126 [Design/#121] 대화 모달 퍼블리싱 완성(?), 로그인페이지에서 쿠키 있으면 이동
  src/components/calender/Calender.tsx
  src/components/common/AudioRecorder.tsx
  src/components/common/Chatting.tsx
  src/components/common/MyMessage.tsx
  src/components/common/OpponentMessage.tsx
  src/pages/ChatPage.tsx
  src/pages/IntroPage.tsx
  src/pages/LogInPage.tsx
  src/pages/SignupPage.tsx
Labels: 🎨Design

#132 [feat/#131] 로그아웃시 토큰 삭제
  src/pages/BookCover.tsx
  src/pages/MainPage.tsx
Labels: ✨Feat

#134 [design/#133] 다이어리 페이지 line-height 재설정
  src/components/common/Diary.tsx
Labels: 🎨Design

#135 [feat/#130] 회원가입 아이디 중복확인 버튼 기능 수정
  src/pages/SignupPage.tsx
Labels: ✨Feat

#138 [feat/#137] 대화 끝내기 컴포넌트 쿼카가 이야기할 때에는 안보이도록 설정
  src/assets/img/QuitIcon2.png
  src/pages/ChatPage.tsx
Labels: ✨Feat

#140 [design#139] 404페이지 퍼블리싱 및 다시시도하시옹
  src/assets/img/404.png
  src/assets/img/F5.png
  src/pages/ChatPage.tsx
  src/pages/Forbidden.tsx
  src/router.tsx
Labels: 🎨Design

#142 [Design/#124] Result Page 구현 및 API 연동
  src/components/common/ChatHistoryInfo.tsx
  src/components/common/Chatting.tsx
  src/components/common/ChattingResult.tsx
  src/components/common/Diary.tsx
  src/components/common/Face.tsx
  src/components/modal/ImageModal.tsx
  src/pages/DiaryPage.tsx
  src/pages/Result.tsx
Labels: 🎨Design, ✨Feat

#143 [feat/#141] 기다려줘 문구, 쿼가가 말하는 도중에 끝내기(마이크) 못 누르게, 쿼카 어화둥둥~
  src/components/common/AudioRecorder.tsx
  src/components/common/CharComponent.tsx
  src/components/gif/Voice.tsx
  src/pages/ChatPage.tsx
  src/stores/chat.ts
Labels: ✨Feat

#144 [Feat/#123] 폴링 구현
  src/assets/img/LoadingQuaka.png
  src/assets/lottie/Load.json
  src/components/calender/Calender.tsx
  src/components/gif/Loading.tsx
  src/components/modal/LoadingModal.tsx
  src/pages/ChatPage.tsx
  src/pages/DiaryPage.tsx
Labels: ✨Feat

#153 [Design/#147] 모달 반응형 생성 및 기본이미지 추가, 일부 빌드 오류 수정
  src/assets/img/DefaultBookCover.png
  src/assets/img/DefaultResultImage.png
  src/components/common/ChatHistoryInfo.tsx
  src/components/common/Face.tsx
  src/components/gif/Loading.tsx
  src/components/modal/CameraModal.tsx
  src/components/modal/ImageModal.tsx
  src/components/modal/LoadingModal.tsx
  src/pages/BookCover.tsx
  src/pages/DiaryPage.tsx
  src/pages/MainPage.tsx
  src/pages/Result.tsx
Labels: 🎨Design

#154 feat: 토큰 만료시 로그아웃 처리 기능 구현
  src/api/config.ts
Labels: ✨Feat

#155 [Feat/#151] 채팅 해결
  src/components/common/CharComponent.tsx
  src/components/common/Chatting.tsx
  src/pages/ChatPage.tsx
Labels: ✨Feat

#156 [Feat/#150] 토큰 없을 때 로그인 페이지로 이동 처리
  src/PrivateRoute.tsx
  src/router.tsx
Labels: ✨Feat

#158 [refactor/#157] result 페이지 Refactoring
  src/components/common/ChatHistoryInfo.tsx
  src/components/common/Face.tsx
  src/pages/Result.tsx
Labels: 🔨Refactor

#166 [feat/#165] diary 대기시간동안 modal 띄우기
  src/components/modal/CameraModal.tsx
Labels: ✨Feat
